apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user1
  title: User 1
  namespace: namespace1
spec:
  profile:
    displayName: User 1
    email: user1@example.com
  memberOf:
    - team1
    - group:namespace2/team2

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user2
  title: User 2
  namespace: namespace1
spec:
  profile:
    displayName: User 2
    email: user2@example.com
  memberOf:
    - team1

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user3
  title: User 3
  namespace: namespace2
spec:
  profile:
    displayName: User 3
    email: user3@example.com
  memberOf:
    - team2

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user4
  title: User 4
  namespace: namespace2
spec:
  profile:
    displayName: User 4
    email: user4@example.com
  memberOf:
    - team2
